#!/usr/bin/env bash
# Assemble what the proxies read: the tracked baseline plus this instance's own additions.
#
#   docker/egress/allow              tracked   the providers — platform content
#   docker/egress/allow.local        ignored   hosts this instance opened for its packages
#   docker/egress/profiles/<n>.allow ignored*  a profile's list (*closed and probe ship tracked)
#          ↓ merged, never edited by hand
#   config/generated/egress/{allow,profiles/<n>.allow}   ← what compose mounts
#
# Why (OPERATIONS §60): which packages an instance runs and what they reach is the instance's
# business, and this repository is public. The same split as config/packages.local.yaml (§42).
set -u
HERE="$(cd "$(dirname "$0")/.." && pwd)"
command -v cygpath >/dev/null && HERE="$(cygpath -m "$HERE")"
SRC="$HERE/docker/egress"
OUT="$HERE/config/generated/egress"
mkdir -p "$OUT/profiles"

merge() {   # <tracked> <overlay> <out>
  {
    printf '# Generated by scripts/egress_gen.sh — edit the sources, not this file.
'
    [ -f "$1" ] && grep -vE '^\s*(#|$)' "$1"
    [ -f "$2" ] && grep -vE '^\s*(#|$)' "$2"
  } > "$3.tmp" && mv "$3.tmp" "$3"
}

merge "$SRC/allow" "$SRC/allow.local" "$OUT/allow"
n=0
for f in "$SRC"/profiles/*.allow; do
  [ -f "$f" ] || continue
  b="$(basename "$f")"
  merge "$SRC/allow" "$f" "$OUT/profiles/$b"
  n=$((n + 1))
done
echo "egress lists generated: shared $(grep -c . "$OUT/allow") rules, $n profile(s)"
